//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alumno
    {
        public Alumno()
        {
            this.Calificacion = new HashSet<Calificacion>();
            this.Deuda = new HashSet<Deuda>();
            this.Matricula = new HashSet<Matricula>();
            this.Pago = new HashSet<Pago>();
        }
    
        public int Alu_Id { get; set; }
        public int Per_Id { get; set; }
        public Nullable<System.DateTime> Alu_FechNac { get; set; }
        public string Alu_Apoderado { get; set; }
        public System.DateTime Alu_FechIngreso { get; set; }
        public bool Alu_Estado { get; set; }
        public string Alu_Foto { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual ICollection<Deuda> Deuda { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual ICollection<Pago> Pago { get; set; }
    }
}
