//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Concepto
    {
        public Concepto()
        {
            this.Costo = new HashSet<Costo>();
            this.Det_Pago = new HashSet<Det_Pago>();
            this.Deuda = new HashSet<Deuda>();
        }
    
        public int Con_Id { get; set; }
        public string Con_Descripcion { get; set; }
    
        public virtual ICollection<Costo> Costo { get; set; }
        public virtual ICollection<Det_Pago> Det_Pago { get; set; }
        public virtual ICollection<Deuda> Deuda { get; set; }
    }
}
