//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Det_Pago
    {
        public int DetPag_Id { get; set; }
        public int Pag_Id { get; set; }
        public int Con_Id { get; set; }
        public string DetPag_Ciclo { get; set; }
    
        public virtual Concepto Concepto { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
