//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Plan
    {
        public int DetPlan_Id { get; set; }
        public int Pla_Id { get; set; }
        public int Pro_Id { get; set; }
    
        public virtual Plan_Estudio Plan_Estudio { get; set; }
        public virtual Programacion Programacion { get; set; }
    }
}
