//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public Horario()
        {
            this.Profesor_Horario = new HashSet<Profesor_Horario>();
        }
    
        public int Hor_Id { get; set; }
        public string Hor_Grupo { get; set; }
        public Nullable<System.TimeSpan> Hor_Ini { get; set; }
        public Nullable<System.TimeSpan> Hor_Fin { get; set; }
        public Nullable<int> Aul_Id { get; set; }
        public Nullable<int> Pro_Id { get; set; }
    
        public virtual Aula Aula { get; set; }
        public virtual Programacion Programacion { get; set; }
        public virtual ICollection<Profesor_Horario> Profesor_Horario { get; set; }
    }
}
