//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matricula
    {
        public int Mat_Id { get; set; }
        public int Mod_Id { get; set; }
        public int Alu_Id { get; set; }
        public string Mat_Tipo { get; set; }
        public System.DateTime Mat_Fecha { get; set; }
        public bool Mat_Estado { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual Modulo Modulo { get; set; }
    }
}
