//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Modulo
    {
        public Modulo()
        {
            this.Calificacion = new HashSet<Calificacion>();
            this.Matricula = new HashSet<Matricula>();
            this.Programacion = new HashSet<Programacion>();
        }
    
        public int Mod_Id { get; set; }
        public string Mod_Nombre { get; set; }
        public string Mod_Tipo { get; set; }
        public string Mod_Unidad { get; set; }
        public string Mod_NumHoras { get; set; }
        public string Mod_NumMes { get; set; }
        public Nullable<int> Mod_Nivel { get; set; }
    
        public virtual ICollection<Calificacion> Calificacion { get; set; }
        public virtual ICollection<Matricula> Matricula { get; set; }
        public virtual ICollection<Programacion> Programacion { get; set; }
    }
}
