//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pago
    {
        public Pago()
        {
            this.Det_Pago = new HashSet<Det_Pago>();
        }
    
        public int Pag_Id { get; set; }
        public Nullable<int> Alu_Id { get; set; }
        public Nullable<System.DateTime> Pag_Fech { get; set; }
    
        public virtual Alumno Alumno { get; set; }
        public virtual ICollection<Det_Pago> Det_Pago { get; set; }
    }
}
