//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plan_Estudio
    {
        public Plan_Estudio()
        {
            this.Detalle_Plan = new HashSet<Detalle_Plan>();
        }
    
        public int Pla_Id { get; set; }
        public string Pla_Nombre { get; set; }
        public string Pla_Distrito { get; set; }
        public string Pla_Ugel { get; set; }
        public string Pla_CetPro { get; set; }
        public Nullable<System.DateTime> Pla_Fechini { get; set; }
        public Nullable<System.DateTime> Pla_Fechfin { get; set; }
    
        public virtual ICollection<Detalle_Plan> Detalle_Plan { get; set; }
    }
}
