//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor_Horario
    {
        public int ProfHor_Id { get; set; }
        public int Prof_Id { get; set; }
        public int Hor_Id { get; set; }
    
        public virtual Horario Horario { get; set; }
        public virtual Profesor Profesor { get; set; }
    }
}
