//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profesor
    {
        public Profesor()
        {
            this.Profesor_Horario = new HashSet<Profesor_Horario>();
        }
    
        public int Prof_Id { get; set; }
        public int Per_Id { get; set; }
        public string Prof_Rpm { get; set; }
        public string Prof_Nextel { get; set; }
        public string Prof_Especialidad { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual ICollection<Profesor_Horario> Profesor_Horario { get; set; }
    }
}
