//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Programacion
    {
        public Programacion()
        {
            this.Detalle_Plan = new HashSet<Detalle_Plan>();
            this.Horario = new HashSet<Horario>();
        }
    
        public int Pro_Id { get; set; }
        public int Mod_Id { get; set; }
        public Nullable<System.DateTime> Pro_Fechaini { get; set; }
        public Nullable<System.DateTime> Pro_Fechafin { get; set; }
    
        public virtual ICollection<Detalle_Plan> Detalle_Plan { get; set; }
        public virtual ICollection<Horario> Horario { get; set; }
        public virtual Modulo Modulo { get; set; }
    }
}
