//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Usuario
    {
        public int TipoUser_Id { get; set; }
        public string TipoUser_Descrip { get; set; }
        public byte TipoUser_Nivel { get; set; }
    }
}
