//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistroIntegral.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public int User_Id { get; set; }
        public int Per_Id { get; set; }
        public string User_Nombre { get; set; }
        public string User_Pass { get; set; }
        public int TipoUser_Id { get; set; }
        public bool User_Estado { get; set; }
    }
}
